import Head from 'next/head';
import { HeadProps } from './SeoHead.types';

const SeoHead = ({ title }: HeadProps) => (
	<Head>
		<title>{title}</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head>
);

export { SeoHead };
